server:
  port: 8001

spring:
  application:
    name: cloud-payment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020
    username: root
    password: Mysqlmima123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com